config/routes.rb
Oenglish::Application.routes.draw do
  

  root 'welcome#index'
  
  devise_for :users, :sign_out_via => [ :post, :delete , :get],  :controllers => {
      registrations: :registrations,
      sessions: :sessions,
      passwords: :passwords
  }
  
  namespace :admin do 
    root "users#index"
    resources :users do
      get :set_grade, :on => :member
      post :do_set, :on => :member
    end
    resources :agents
    resources :courses
    resources :lessons
    resources :grades
    resources :schedules do
      get :meeting, :on => :member
      get :webex, :on => :member
    end
    resources :coursewares
  end
  
  namespace :agent do
    root "students#index"
    resources :students
  end
  
  namespace :teacher do
    root "schedules#index"
    resources :schedules
  end
  
  namespace :student do
    root "courses#index"
    resources :courses
    resources :schedules do
      get :enroll,  :on => :collection
    end
    resources :coursewares
  end
  
  

  

end

app/models/courseware.rb
class Courseware < ActiveRecord::Base
  has_attached_file :ppt
  validates_attachment_presence :ppt 
  validates_attachment_content_type :ppt, :content_type => ['application/pdf',
                                              'application/vnd.ms-powerpoint',
                                              'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                                              "application/vnd.ms-excel",     
                                              "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                              "application/msword", 
                                              "application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
                                              "text/plain"],
                                    :message => ', Only PDF, PPT, Word, Excel, TXT files are allowed. '
  
end

app/controllers/admin/coursewares_controller.rb
class Admin::CoursewaresController < Admin::BaseController
  
  def index
    @q = Courseware.search(params[:q])
    @coursewares = @q.result(distinct: true).page(params[:page])
  end
  
  def new
    @courseware = Courseware.new
  end
  
  def create
    begin
      Courseware.create!(courseware_params)
      flash[:notice] = "Success"
    rescue Exception => e
      flash[:notice] = e.message
    end
    redirect_to admin_coursewares_path
  end
  
  def edit
    @courseware = Courseware.find_by_id(params[:id])
  end
  
  def update
    user = Courseware.find_by_id(params[:id])
    begin
      user.update!(courseware_params)
      flash[:notice] = "Success"
    rescue Exception => e
      flash[:notice] = e.message
    end
    redirect_to admin_coursewares_path
  end
  
  def destroy
    flash[:notice] = Courseware.find_by_id(params[:id]).destroy ? "Success" : "Fail"
    redirect_to admin_coursewares_path
  end
  

  private
  def courseware_params
    params.require(:courseware).permit(:position,:name,:desc,:ppt)
  end
  
end

app/controllers/student/coursewares_controller.rb
class Student::CoursewaresController < Student::BaseController
  
  def index
    @q = Courseware.search(params[:q])
    @coursewares = @q.result(distinct: true).page(params[:page])
  end
  
end

app/helpers/admin/coursewares_helper.rb
module Admin::CoursewaresHelper
end

app/helpers/student/coursewares_helper.rb
module Student::CoursewaresHelper
end

app/views/admin/coursewares/_breadcrumb.html.erb
<ol class="breadcrumb">
  <li><%= link_to t(:admin_coursewares), admin_coursewares_path %></li>
  <li><%= link_to t(:new_courseware), new_admin_courseware_path(), :class => "btn btn-info" %></li>
</ol>

app/views/admin/coursewares/_form.html.erb
<%= form_for @courseware, url: url,  html: {class: "form-horizontal", :multipart => true} do |f| %>
	<% %w{position name}.each do |item| %>
		<div class="form-group">
			<%= f.label t("c_#{item}"), :for => "courseware_#{item}", :class => "col-sm-2 control-label"%>
			<div class="col-sm-10">
				<%= f.text_field item.to_sym, :class => "form-control", :placeholder => t("c_#{item}") %>
		    </div>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label t(:desc), :for => "courseware_desc", :class => "col-sm-2 control-label"%>
		<div class="col-sm-10">
			<%= f.text_area :desc, :class => "form-control" %>
	    </div>
	</div>
	<div class="form-group">
		<%= f.label t(:ppt), :for => "courseware_ppt", :class => "col-sm-2 control-label"%>
		<div class="col-sm-10">
			<%= f.file_field :ppt, :class => "form-control" %>
	    </div>
	</div>
	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
			<%= f.button t(:submit), :class => "btn btn-default"%>
	    </div>
	  </div>
<% end %>

app/views/admin/coursewares/_search.html.erb
<div class="well">
	<%= search_form_for @q, url: admin_coursewares_path, :role => "form", :class => "form-inline" do |f| %>
	  <%= f.text_field :name_cont, {:placeholder => t(:c_name),:class => "form-control"} %>
	  <%= f.submit :search, {:class => "btn btn-default"} %>
	<% end %>
</div>

app/views/admin/coursewares/edit.html.erb
<%= render :partial => "breadcrumb"%>
<div>
	<h2><%= t(:edit)%></h2>
</div>
<%= render :partial => "form", :locals => {:url => admin_courseware_path(@courseware)}%>

app/views/admin/coursewares/index.html.erb
<%= render :partial => "breadcrumb" %>

<%= render :partial => "search" %>

<div class="table-responsive">
  <table class="table table-striped">
		<tr>
			<td><%= t(:c_position)%></td>
			<td><%= t(:c_name) %></td>
			<td><%= t(:desc) %></td>
			<td><%= t(:ppt)%></td>
			<td><%= t(:actions)%></td>
		</tr>
		<% @coursewares.each do |courseware| %>
			<tr>
				<td><%= courseware.position %></td>
				<td><%= courseware.name %></td>
				<td><%= courseware.desc %></td>
				<td><%= link_to t(:download), courseware.ppt.url %></td>
				<td>
					<%= link_to t(:edit), edit_admin_courseware_path(courseware), :class => "btn btn-default" %>
					<%= link_to t(:delete), admin_courseware_path(courseware),:method => :delete, :class => "btn btn-danger", confirm: "Are you sure?"%>
					
				</td>
			</tr>	
		<% end %>	
  </table>
  <%= paginate @coursewares%>
</div>

app/views/admin/coursewares/new.html.erb
<%= render :partial => "breadcrumb"%>
<div>
	<h2><%= t("new_courseware")%></h2>
</div>
<%= render :partial => "form", :locals => {:url => admin_coursewares_path}%>