config/routes.rb
Oenglish::Application.routes.draw do
  

  root 'welcome#index'
  
  devise_for :users, :sign_out_via => [ :post, :delete , :get],  :controllers => {
      registrations: :registrations,
      sessions: :sessions,
      passwords: :passwords
  }
  
  namespace :admin do 
    root "users#index"
    resources :users do
      get :set_grade, :on => :member
      post :do_set, :on => :member
    end
    resources :agents
    resources :courses
    resources :lessons
    resources :grades
    resources :schedules do
      get :meeting, :on => :member
      get :webex, :on => :member
    end
    resources :coursewares
  end
  
  namespace :agent do
    root "students#index"
    resources :students
  end
  
  namespace :teacher do
    root "schedules#index"
    resources :schedules
  end
  
  namespace :student do
    root "courses#index"
    resources :courses
    resources :schedules do
      get :enroll,  :on => :collection
    end
    resources :coursewares
  end
  
  

  

end

app/models/agent.rb
class Agent < ActiveRecord::Base
  belongs_to :user
  has_many  :students,  :class_name => User
  
  def top_agent
    Agent.find_by_id(self.top_id)
  end
  
end

app/controllers/admin/agents_controller.rb
class Admin::AgentsController < Admin::BaseController
  
  def index
    @q = Agent.search(params[:q])
    @agents = @q.result(distinct: true).page(params[:page])
  end
  
  def new
    @agent = Agent.new
  end
  
  def create
    begin
      Agent.create!(agent_params)
      flash[:notice] = "Success"
    rescue Exception => e
      flash[:notice] = e.message
    end
    redirect_to admin_agents_path
  end
  
  def edit
    @agent = Agent.find_by_id(params[:id])
  end
  
  def update
    agent = Agent.find_by_id(params[:id])
    begin
      agent.update!(agent_params)
      flash[:notice] = "Success"
    rescue Exception => e
      flash[:notice] = e.message
    end
    redirect_to admin_agents_path
  end
  
  def destroy
    flash[:notice] = Agent.find_by_id(params[:id]).destroy ? "Success" : "Fail"
    redirect_to admin_agents_path
  end
  
  def show
    @agent = Agent.find_by_id(params[:id])
  end
  
  
  private
  def agent_params
    params.require(:agent).permit(:user_id, :top_id,:name,:contract_no,:commission_x,  :commission_ya, :commission_yb,  :commission_z,:a_type,:logo)
  end
  
end

app/controllers/agent/base_controller.rb
class Agent::BaseController < ApplicationController
  layout "agent"
  before_action :authenticate_user!
  before_filter :check_agent?
  helper_method :current_agent
  
  def check_agent?
    redirect_to root_path unless current_user.is_agent?
  end
  
  def current_agent
    Agent.where({user_id: current_user.id}).first
  end
  
end

app/controllers/agent/students_controller.rb
class Agent::StudentsController < Agent::BaseController
  
  def index
    unless current_agent.blank?
      @q = User.search((params[:q] || {}).merge({:agent_id_eq => current_agent.id}))
      @students = @q.result(distinct: true).page(params[:page])
    else
      flash[:notice] = "This account donot bind with agent!"
    end
  end
  
end

app/helpers/admin/agents_helper.rb
module Admin::AgentsHelper
  
  def agent_type
    ["person","school","intermedia","tutorial","training","visa_center"]
  end
  
  def user_agents_list
    User.agents.pluck(:name,:id)
  end
  
  def agents_list
    Agent.all.pluck(:name,:id)
  end
  
end

app/helpers/agent/students_helper.rb
module Agent::StudentsHelper
end

app/views/admin/agents/_breadcrumb.html.erb
<ol class="breadcrumb">
  <li><%= link_to t(:admin_agents), admin_agents_path %></li>
  <!-- <li><%#= link_to t(:new_agent), new_admin_agent_path(), :class => "btn btn-info" %></li> -->
</ol>

app/views/admin/agents/_form.html.erb
<%= form_for @agent, url: url,  html: {class: "form-horizontal"} do |f| %>
	<!-- <div class="form-group">
		<%#= f.label t(:user_id), :for => "agent_user_id", :class => "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%#= f.select :user_id, user_agents_list,{}, {:class => "form-control"} %>
		</div>
	</div> -->
	<% %w{name contract_no commission_x commission_ya commission_yb commission_z}.each do |item| %>
		<div class="form-group">
			<%= f.label t(item), :for => "agent_#{item}", :class => "col-sm-2 control-label"%>
			<div class="col-sm-10">
				<%= f.text_field item.to_sym, :class => "form-control", :placeholder => t(item) %>
		    </div>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label t(:a_type), :for => "agent_a_type", :class => "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.select :a_type, agent_type,{}, {:class => "form-control"}%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label t(:top_id), :for => "agent_top_id", :class => "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.select :top_id, [[nil,nil]] + agents_list,{}, {:class => "form-control"}%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label t(:logo), :for => "agent_logo", :class => "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.select :logo, [true,false],{},{:class => "form-control"}%>
		</div>
	</div>
	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
			<%= f.button t(:submit), :class => "btn btn-default"%>
	    </div>
	  </div>
<% end %>

app/views/admin/agents/_search.html.erb
<div class="well">
	<%= search_form_for @q, url: admin_agents_path, :role => "form", :class => "form-inline" do |f| %>
	  <%= f.text_field :name_cont, {:placeholder => t(:name),:class => "form-control"} %>
	  <%= f.text_field :contract_no_cont,{:placeholder => t(:contract_no),:class => "form-control"} %>
	  <%= f.select :a_type_eq, ([''] + agent_type).flatten, {}, {:class => "form-control"} %>
	  <%= f.submit :search, {:class => "btn btn-default"} %>
	<% end %>
</div>

app/views/admin/agents/_students.html.erb
<table class="table table-striped">
	<tr>
		<td><%= t(:name)%></td>
		<td><%= t(:login) %></td>
		<td><%= t(:email) %></td>
		<td><%= t(:created_at)%></td>
	</tr>
	<% @agent.students.each do |student| %>
		<tr>
			<% %w{name login email}.each do |item| %>
				<td><%= student.send(item)%></td>
			<% end %>
			<td>
				<%= student.created_at.strftime("%Y-%m-%d %H:%M")%>
			</td>
		</tr>	
	<% end %>
</table>

app/views/admin/agents/edit.html.erb
<%= render :partial => "breadcrumb"%>
<div>
	<h2><%= t(:edit)%></h2>
</div>
<%= render :partial => "form", :locals => {:url => admin_agent_path(@agent)}%>

app/views/admin/agents/index.html.erb
<%= render :partial => "breadcrumb" %>

<%= render :partial => "search" %>

<div class="table-responsive">
  <table class="table table-striped">
		<tr>
			<td><%= t(:name)%></td>
			<td><%= t(:email)%></td>
			<td><%= t(:contract_no) %></td>
			<td><%= t(:top_id) %></td>
			<td><%= t(:a_type) %></td>
			<td><%= t(:students) %></td>
			<td><%= t(:actions)%></td>
		</tr>
		<% @agents.each do |agent| %>
			<tr>
				<td><%= agent.name %></td>
				<td><%= agent.user.email%></td>
				<td><%= agent.contract_no %></td>
				<td><%= agent.top_agent.try(:name) %></td>
				<td><%= agent.a_type %></td>
				<td><%= link_to agent.students.count, admin_agent_path(agent) %></td>
				<td>
					<%= link_to t(:show), admin_agent_path(agent), :class => "btn btn-default" %>
					<%= link_to t(:edit), edit_admin_agent_path(agent), :class => "btn btn-default" %>
					<%= link_to t(:delete), admin_agent_path(agent),:method => :delete, :class => "btn btn-danger", :confirm => "Are you sure?"%>
				</td>
			</tr>	
		<% end %>	
  </table>
  <%= paginate @agents%>
</div>

app/views/admin/agents/new.html.erb
<%= render :partial => "breadcrumb"%>
<div>
	<h2><%= t("new_agent")%></h2>
</div>
<%= render :partial => "form", :locals => {:url => admin_agents_path}%>

app/views/admin/agents/show.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><%= t(:agent_info) %></div>
  <div class="panel-body">
    <p><%= t(:name) %>: <%= @agent.name %></p>
  </div>

  <!-- Table -->
  <%= render :partial => "students"%>
</div>