config/routes.rb
Oenglish::Application.routes.draw do
  

  root 'welcome#index'
  
  devise_for :users, :sign_out_via => [ :post, :delete , :get],  :controllers => {
      registrations: :registrations,
      sessions: :sessions,
      passwords: :passwords
  }
  
  namespace :admin do 
    root "users#index"
    resources :users do
      get :set_grade, :on => :member
      post :do_set, :on => :member
    end
    resources :agents
    resources :courses
    resources :lessons
    resources :grades
    resources :schedules do
      get :meeting, :on => :member
      get :webex, :on => :member
    end
    resources :coursewares
  end
  
  namespace :agent do
    root "students#index"
    resources :students
  end
  
  namespace :teacher do
    root "schedules#index"
    resources :schedules
  end
  
  namespace :student do
    root "courses#index"
    resources :courses
    resources :schedules do
      get :enroll,  :on => :collection
    end
    resources :coursewares
  end
  
  

  

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :grade
  belongs_to :teacher,  :class_name => User,  :foreign_key => :teacher_id
  
  def self.generate_pwd
    range = ("A".."Z").to_a + ("0".."9").to_a
    pwd = ""
    (1..8).each do |n|
      pwd += range[rand * range.size]
    end
    return pwd
  end
  
  def params_for_webex_create_meeting(back_url)
    params = {}
    params[:EN] = self.title
    params[:JPW] = self.webex_pwd
    params[:YE] = self.start_at.year
    params[:MO] = self.start_at.month
    params[:DA] = self.start_at.day
    params[:HO] = self.start_at.hour
    params[:MI] = self.start_at.min
    params[:DU] = (self.end_at - self.start_at).to_i/60
    params[:BU] = back_url
    params
  end
  
  def is_active
    t = Time.zone.now
    return ((self.start_at - 15.minutes) <= t and t <= self.end_at)
  end
  
end

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < Admin::BaseController
  
  def index
    @q = Schedule.search(params[:q])
    @schedules = @q.result(distinct: true).page(params[:page])
  end
  
  def new
    @schedule = Schedule.new(schedule_params)
  end
  
  def create
    begin
      schedule = Schedule.create!(schedule_params)
      redirect_to meeting_admin_schedule_path(schedule)
    rescue Exception => e
      flash[:notice] = e.message
      redirect_to admin_schedules_path
    end    
  end
  
  # this is for create meeting in webex
  def meeting
    
    schedule = Schedule.find_by_id(params[:id])
    back_url = oenglish_url(webex_admin_schedule_path(schedule))
    w_params = schedule.params_for_webex_create_meeting(back_url)
    redirect_to Webex::UrlApi.new.schedule_meeting(w_params)
  end
  
  # this is for receiving feedback from webex
  def webex
    webex_no = params[:MK]    
    if webex_no.present?      
      schedule = Schedule.find_by_id(params[:id])
      flash[:notice] = schedule.update_columns(:webex_no => webex_no) ? "Success" : "Update Fail"
    else
      flash[:notice] = "Fail to create webex, error message: #{params[:RS]} "
    end
    redirect_to admin_schedules_path
  end
  
  
  def edit
    @schedule = Schedule.find_by_id(params[:id])
  end
  
  def update
    user = Schedule.find_by_id(params[:id])
    begin
      user.update!(schedule_params)
      flash[:notice] = "Success"
    rescue Exception => e
      flash[:notice] = e.message
    end
    redirect_to admin_schedules_path
  end
  
  def destroy
    flash[:notice] = Schedule.find_by_id(params[:id]).destroy ? "Success" : "Fail"
    redirect_to admin_schedules_path
  end
  

  private
  def schedule_params
    params.require(:schedule).permit(:title,:teacher_id,:grade_id,:start_at,:end_at,:webex_pwd)
  end
  
end

app/controllers/student/schedules_controller.rb
class Student::SchedulesController < Student::BaseController
  
  def index
    grades_id = current_user.grades.opened.pluck(:id)
    if grades_id.blank?
      @schedules = []
    else
      h = {:grade_id_in => grades_id}
      unless params[:num].blank?
        @num = params[:num] || "0"
        d = Time.now.to_date
        date = d + @num.to_i.days
        h[:start_at_gteq] = date.beginning_of_day
        h[:start_at_lteq] = date.end_of_day
      else
        h[:start_at_lt] = Time.now.beginning_of_day  
      end
      @q = Schedule.search((params[:q] || {}).merge(h))
      @schedules = @q.result(distinct: true).page(params[:page])
    end
  end
  
  # enroll meeting and join meeting
  def show
    meeting = Schedule.find_by_id(params[:id])
    wx = Webex::UrlApi.new
    if current_user.enroll_meeting?(meeting)
      j_params = current_user.join_enrolled_meeting_params(meeting)
      back_url = oenglish_url(student_schedules_path)
      redirect_to wx.join_enrolled_meeting(j_params,back_url)
    else
      back_url = oenglish_url(enroll_student_schedules_path(:SID => meeting.id,:WID => meeting.webex_no,:PWD => meeting.webex_pwd))
      e_params = current_user.enroll_meeting_params(meeting)
      redirect_to wx.enroll_meeting(e_params,back_url)
    end
  end
  
  # enroll meeting
  def enroll
    begin
      EnrollWebex.create!({:enroll_id => params[:EI], :user_id => current_user.id, :schedule_id => params[:SID]})
      wx = Webex::UrlApi.new
      meeting = Schedule.find_by_id(params[:SID])
      j_params = current_user.join_enrolled_meeting_params(meeting)
      back_url = oenglish_url(student_schedules_path)
      redirect_to wx.join_enrolled_meeting(j_params,back_url)
    rescue Exception => e
      flash[:notice] = "You enrolled webex fail! error message : #{e.message}"
      redirect_to student_schedules_path
    end
  end
  
end

app/controllers/teacher/schedules_controller.rb
class Teacher::SchedulesController < Teacher::BaseController
  
  def index
    h = {:teacher_id_eq => current_user.id}
    @num = params[:num]
    unless @num.blank?
      d = Time.now.to_date
      date = d + @num.to_i.days
      h[:start_at_gteq] = date.beginning_of_day
      h[:start_at_lteq] = date.end_of_day
    end
    @q = Schedule.search((params[:q] || {}).merge(h))
    @schedules = @q.result(distinct: true).page(params[:page])
  end
  
  # start meeting
  def show
    schedule = Schedule.find_by_id(params[:id])
    wx = Webex::UrlApi.new
    back_url = oenglish_url(teacher_schedules_path)
    redirect_to wx.login(wx.start_meeting(schedule.webex_no, back_url))
  end
  
end

app/helpers/admin/schedules_helper.rb
module Admin::SchedulesHelper
  
  def grades_list
    Grade.all.pluck(:name,:id)
  end
  
end

app/helpers/student/schedules_helper.rb
module Student::SchedulesHelper
end

app/helpers/teacher/schedules_helper.rb
module Teacher::SchedulesHelper
end

app/views/admin/schedules/_breadcrumb.html.erb
<ol class="breadcrumb">
	<li><%= link_to t(:admin_grades), admin_grades_path %></li>
  	<li><%= link_to t(:admin_schedules), admin_schedules_path %></li>
  	<li><%= link_to t(:new_schedule), new_admin_schedule_path(:schedule => {:webex_pwd => Schedule.generate_pwd}), :class => "btn btn-info" %></li>
</ol>

app/views/admin/schedules/_form.html.erb
<%= form_for @schedule, url: url,  html: {class: "form-horizontal"} do |f| %>
	<div class="form-group">
		<%= f.label t(:teacher_id), :for => "schedule_teacher_id", :class => "col-sm-2 control-label"%>
		<div class="col-sm-10">
			<%= f.select :teacher_id, teachers_list, {}, :class => "form-control" %>
	    </div>
	</div>
	<div class="form-group">
		<%= f.label t(:grade_id), :for => "schedule_grade_id", :class => "col-sm-2 control-label"%>
		<div class="col-sm-10">
			<%= f.select :grade_id, grades_list, {}, :class => "form-control" %>
	    </div>
	</div>
	<div class="form-group">
		<%= f.label t(:title), :for => "schedule_title", :class => "col-sm-2 control-label"%>
		<div class="col-sm-10">
			<%= f.text_field :title, :class => "form-control", :placeholder => t(:title) %>
	    </div>
	</div>
	<div class="form-group">
		<%= f.label t(:start_at), :for => "schedule_start_at", :class => "col-sm-2 control-label"%>
		<div class="col-sm-10">
			<%= f.datetime_select :start_at, :class => "form-control", :placeholder => t(:start_at) %>
	    </div>
	</div>
	<div class="form-group">
		<%= f.label t(:end_at), :for => "schedule_start_at", :class => "col-sm-2 control-label"%>
		<div class="col-sm-10">
			<%= f.datetime_select :end_at, :class => "form-control", :placeholder => t(:end_at) %>
	    </div>
	</div>
	<%= f.hidden_field :webex_pwd %>
	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
			<%= f.button t(:submit), :class => "btn btn-default"%>
	    </div>
	  </div>
<% end %>

app/views/admin/schedules/_search.html.erb
<div class="well">
	<%= search_form_for @q, url: admin_schedules_path, :role => "form", :class => "form-inline" do |f| %>
	  <%= f.text_field :title_cont, {:placeholder => t(:title),:class => "form-control"} %>&nbsp;&nbsp;&nbsp;&nbsp;
	  <%= f.label t(:teacher_id), :class => "control-label"%>
	  <%= f.select :teacher_id_eq, ([[nil,nil]] + teachers_list), {}, {:class => "form-control"} %>&nbsp;&nbsp;&nbsp;&nbsp;
	  <%= f.label t(:grade_id), :class => "control-label"%>
	  <%= f.select :grade_id_eq, ([[nil,nil]] + grades_list), {}, {:class => "form-control"} %>
	  <%= f.submit :search, {:class => "btn btn-default"} %>
	<% end %>
</div>

app/views/admin/schedules/edit.html.erb
<%= render :partial => "breadcrumb"%>
<div>
	<h2><%= t(:edit)%></h2>
</div>
<%= render :partial => "form", :locals => {:url => admin_schedule_path(@schedule)}%>

app/views/admin/schedules/index.html.erb
<%= render :partial => "breadcrumb" %>

<%= render :partial => "search" %>

<div class="table-responsive">
  <table class="table table-striped">
		<tr>
			<td><%= t(:title) %></td>
			<td><%= t(:class_name)%></td>	
			<td><%= t(:teacher_id)%></td>			
			<td><%= t(:start_at) %></td>
			<td><%= t(:end_at)%></td>
			<td><%= t(:webex_no) %></td>
			<td><%= t(:webex_pwd)%></td>
			<td><%= t(:actions)%></td>
		</tr>
		<% @schedules.each do |schedule| %>
			<tr>				
				<td><%= schedule.title %></td>
				<td><%= schedule.grade.try(:name)%></td>
				<td><%= schedule.teacher.try(:name) %></td>
				<td><%= schedule.start_at.try(:strftime, "%Y-%m-%d %H:%M") %></td>
				<td><%= schedule.end_at.try(:strftime, "%Y-%m-%d %H:%M")  %></td>
				<td><%= schedule.webex_no %></td>
				<td><%= schedule.webex_pwd %></td>
				<td>										
					<% if schedule.webex_no.blank? %>
						<%= link_to t(:edit), edit_admin_schedule_path(schedule), :class => "btn btn-default" %>
						<%= link_to t(:to_webex), meeting_admin_schedule_path(schedule), :class => "btn btn-default" %>
						<%= link_to t(:delete), admin_schedule_path(schedule),:method => :delete, :class => "btn btn-danger", :confirm => "Are you sure?"%>
					<% end %>
				</td>
			</tr>	
		<% end %>	
  </table>
  <%= paginate @schedules%>
</div>

<script>
	function webex_login(){
		$.ajax({
			data: {
				AT: "LI",
				PW: "<%= Webex::UrlApi::PWD %>",
				WID: "<%= Webex::UrlApi::USER %>"
			},
			dataType: "script",
			type: "GET",
			url: "<%= Webex::UrlApi::BASEURL %>" + "p.php",
			success: function(data,textStatus){
				webex_set_meeting_type();
			}
		});
	}
	
	function webex_set_meeting_type(){
		$.ajax({
			data: {
				AT: "ST",
				SP: "EC"
			},
			dataType: "script",
			type: "GET",
			url: "<%= Webex::UrlApi::BASEURL %>" + "o.php",
			success: function(data, textStatus){
				
			}
		})
	}

	$(function(){
		webex_login();
	})
</script>

app/views/admin/schedules/new.html.erb
<%= render :partial => "breadcrumb"%>
<div>
	<h2><%= t("new_schedule")%></h2>
</div>
<%= render :partial => "form", :locals => {:url => admin_schedules_path}%>