config/routes.rb
Oenglish::Application.routes.draw do
  

  root 'welcome#index'
  
  devise_for :users, :sign_out_via => [ :post, :delete , :get],  :controllers => {
      registrations: :registrations,
      sessions: :sessions,
      passwords: :passwords
  }
  
  namespace :admin do 
    root "users#index"
    resources :users do
      get :set_grade, :on => :member
      post :do_set, :on => :member
    end
    resources :agents
    resources :courses
    resources :lessons
    resources :grades
    resources :schedules do
      get :meeting, :on => :member
      get :webex, :on => :member
    end
    resources :coursewares
  end
  
  namespace :agent do
    root "students#index"
    resources :students
  end
  
  namespace :teacher do
    root "schedules#index"
    resources :schedules
  end
  
  namespace :student do
    root "courses#index"
    resources :courses
    resources :schedules do
      get :enroll,  :on => :collection
    end
    resources :coursewares
  end
  
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :agent
  has_and_belongs_to_many :grades
  has_many  :grades_users
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :agents, -> {where(u_type: :agent)}
  scope :students, -> {where(u_type: :student)}
  scope :teachers, -> {where(u_type: :teacher)}
  scope :admins, -> {where(u_type: :admin)}   
  
  after_create :create_agent
  
  def create_agent
    if self.u_type == "agent"
      Agent.create(:user_id => self.id, :name => self.name)
    end
  end    
  
  def is_admin?
    return self.u_type == "admin"
  end
  
  def is_student?
    return self.u_type == "student"
  end
  
  def is_teacher?
    return self.u_type == "teacher"
  end
  
  def is_agent?
    return self.u_type == "agent"
  end
  
  def asigned_grades
    case self.u_type
    when "student"
      self.grades
    when "teacher"
      Grade.where(:teacher_id => self.id)
    else
      nil
    end
  end
  
  def enroll_meeting_params(schedule)
    params = {}
    params["AE"] = self.email
    params["FN"] = self.name || "fname"
    params["LN"] = self.login || "lname"
    params["MK"] = schedule.webex_no
    params
  end
  
  def join_enrolled_meeting_params(schedule)
    params = {}
    ew = EnrollWebex.where(:user_id => self.id, :schedule_id => schedule.id).first
    params["EI"] = ew.enroll_id
    params["MK"] = schedule.webex_no
    params["JPW"] = schedule.webex_pwd
    params
  end
  
  def enroll_meeting?(schedule)
    ew = EnrollWebex.where(:user_id => self.id, :schedule_id => schedule.id)
    return (ew.blank? ? false : true) 
  end
  
  def to_agent
    Agent.find_by_id(self.agent_id)
  end
         
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  
  def index
    @q = User.search(params[:q])
    @users = @q.result(distinct: true).page(params[:page])
  end
  
  def new
    @user = User.new(user_params)
  end
  
  def create
    begin
      User.create!(user_params)
      flash[:notice] = "Success"
    rescue Exception => e
      flash[:notice] = e.message
    end
    redirect_to admin_users_path
  end
  
  def edit
    @user = User.find_by_id(params[:id])
    render (params[:flag].blank? ? "edit" : "password")
  end
  
  def update
    user = User.find_by_id(params[:id])
    begin
      user.update!(user_params)
      flash[:notice] = "Success"
    rescue Exception => e
      flash[:notice] = e.message
    end
    redirect_to admin_users_path
  end
  
  def show
    @user = User.find_by_id(params[:id])
  end
  
  def set_grade
    @user = User.find_by_id(params[:id])
    @grades = Grade.opened
  end
  
  # tomorrow do this at 20140502
  def do_set
    begin
      user = User.find_by_id(params[:id])
      user.grades_users.create!(:grade_id => params[:grade_id], :deadline => params[:deadline])
      flash[:notice] = "Set Success"
    rescue Exception => e
      flash[:notice] = "Set Fail, error message: #{e.message}"
    end
    redirect_to admin_users_path
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:login,:email,:password,:u_type)
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  
  def user_type
    ["student","teacher", "agent", "admin"]
  end
  
end

app/views/admin/users/_breadcrumb.html.erb
<ol class="breadcrumb">
  <li><%= link_to t(:admin_users), admin_users_path %></li>
  <li><%= link_to t(:new_teacher), new_admin_user_path(:user => {:u_type => "teacher"}), :class => "btn btn-info" %></li>
  <li><%= link_to t(:new_admin), new_admin_user_path(:user => {:u_type => "admin"}), :class => "btn btn-primary" %></li>
  <li><%= link_to t(:new_agent), new_admin_user_path(:user => {:u_type => "agent"}), :class => "btn btn-primary" %></li>
</ol>

app/views/admin/users/_form.html.erb
<%= form_for @user, url: url,  html: {class: "form-horizontal"} do |f| %>
	<% %w{email login name password}.each do |item| %>
		<div class="form-group">
			<%= f.label t(item), :for => "user_#{item}", :class => "col-sm-2 control-label"%>
			<div class="col-sm-10">
				<%= f.text_field item.to_sym, :class => "form-control", :placeholder => t(item) %>
		    </div>
		</div>
	<% end %>
	<%= f.hidden_field :u_type %>
	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
			<%= f.button t(:submit), :class => "btn btn-default"%>
	    </div>
	  </div>
<% end %>

app/views/admin/users/_grades.html.erb
<% grades = @user.asigned_grades %>
<% unless grades.blank? %>
	<div class="table-responsive">
	  <table class="table table-striped">
			<tr>
				<td><%= t(:c_name)%></td>			
				<td><%= t(:num_of_students) %></td>
				<td><%= t(:start_date) %></td>
				<td><%= t(:start_hour) %></td>
				<td><%= t(:start_minute) %></td>
				<td><%= t(:duration) %></td>
				<td><%= t(:repeat_wday) %></td>
				<td><%= t(:status) %></td>
				<td><%= t(:students)%></td>
			</tr>
			<% grades.each do |grade| %>
				<tr>
					<% %w{name num_of_students start_date start_hour start_minute duration repeat_wday status}.each do |item| %>
						<td><%= grade.send(item)%></td>
					<% end %>
					<td><%= grade.users.count %></td>
				</tr>	
			<% end %>	
	  </table>
	</div>
<% end %>	

app/views/admin/users/_grades_users.html.erb
<% grades_users = @user.grades_users %>
<% unless grades_users.blank? %>
	<div class="table-responsive">
	  <table class="table table-striped">
			<tr>
				<td><%= t(:teacher_id) %></td>
				<td><%= t(:c_name)%></td>			
				<td><%= t(:num_of_students) %></td>
				<td><%= t(:start_date) %></td>
				<td><%= t(:start_hour) %></td>
				<td><%= t(:start_minute) %></td>
				<td><%= t(:duration) %></td>
				<td><%= t(:repeat_wday) %></td>
				<td><%= t(:deadline) %></td>
				<td><%= t(:students)%></td>
			</tr>
			<% grades_users.each do |g_user| %>
				<% grade = g_user.grade %>
				<tr>
					<td><%= grade.teacher.try(:name) %></td>
					<% %w{name num_of_students start_date start_hour start_minute duration repeat_wday}.each do |item| %>
						<td><%= grade.send(item)%></td>
					<% end %>
					<td><%= g_user.deadline %></td>
					<td><%= grade.users.count %></td>
				</tr>	
			<% end %>	
	  </table>
	</div>
<% end %>

app/views/admin/users/_search.html.erb
<div class="well">
	<%= search_form_for @q, url: admin_users_path, :role => "form", :class => "form-inline" do |f| %>
	  <%= f.text_field :name_cont, {:placeholder => t(:name),:class => "form-control"} %>
	  <%= f.text_field :email_cont,{:placeholder => t(:email),:class => "form-control"} %>
	  <%= f.select :u_type_eq, ([''] + user_type).flatten, {}, {:class => "form-control"} %>
	  <%= f.submit :search, {:class => "btn btn-default"} %>
	<% end %>
</div>

app/views/admin/users/edit.html.erb
<%= render :partial => "breadcrumb"%>
<div>
	<h2><%= t(:edit)%></h2>
</div>
<%= render :partial => "form", :locals => {:url => admin_user_path(@user)}%>

app/views/admin/users/index.html.erb
<%= render :partial => "breadcrumb" %>

<%= render :partial => "search" %>

<div class="table-responsive">
  <table class="table table-striped">
		<tr>
			<td><%= t(:name)%></td>
			<td><%= t(:login) %></td>
			<td><%= t(:email) %></td>
			<td><%= t(:u_type) %></td>
			<td><%= t(:grades) %></td>
			<td><%= t(:to_agent)%></td>
			<td><%= t(:actions)%></td>
		</tr>
		<% @users.each do |user| %>
			<tr>
				<% %w{name login email u_type}.each do |item| %>
					<td><%= user.send(item)%></td>
				<% end %>
				<td><%= user.asigned_grades.try(:count) %></td>
				<td><%= user.to_agent.try(:name)%></td>
				<td>
					<%= link_to t(:show), admin_user_path(user), :class => "btn btn-default" %>
					<%= link_to t(:edit), edit_admin_user_path(user), :class => "btn btn-default" %>
					<% if user.is_student? %>
						<%= link_to t(:set_grade), set_grade_admin_user_path(user), :class => "btn btn-info"%>
					<% end %>
					<%= link_to t(:password), edit_admin_user_path(user, :flag => "password"), :class => "btn btn-default" %>
				</td>
			</tr>	
		<% end %>	
  </table>
  <%= paginate @users%>
</div>

app/views/admin/users/new.html.erb
<%= render :partial => "breadcrumb"%>
<div>
	<h2><%= t("new_#{@user.u_type}")%></h2>
</div>
<%= render :partial => "form", :locals => {:url => admin_users_path}%>

app/views/admin/users/password.html.erb
<%= form_for @user, url: admin_user_path(@user),  html: {class: "form-horizontal"} do |f| %>
	<div class="form-group">
		<%= f.label t(:password), :for => "user_password", :class => "col-sm-2 control-label"%>
		<div class="col-sm-10">
			<%= f.password_field :password, :class => "form-control", :placeholder => t(:password)  %>
	    </div>
	</div>
	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
			<%= f.button t(:submit), :class => "btn btn-default"%>
	    </div>
	  </div>
<% end %>

app/views/admin/users/set_grade.html.erb
<%= form_tag do_set_admin_user_path(@user), method: :post,  :class => "form-horizontal" do |f| %>
	<div class="form-group">
		<%= label_tag :grade, t(:grade), :class => "col-sm-2 control-label"%>
		<div class="col-sm-10">
			<%= select_tag :grade_id, options_from_collection_for_select(Grade.opened,:id,:name), :class => "form-control" %>
	    </div>
	</div>
	<div class="form-group">
		<%= label_tag :deadline, t(:deadline), :class => "col-sm-2 control-label"%>
		<div class="col-sm-10">
			<%= text_field_tag :deadline, (Time.now + 1.month).to_date, :class => "form-control" %>
	    </div>
	</div>
	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
			<%= button_tag t(:submit), :class => "btn btn-default"%>
	    </div>
	  </div>
<% end %>

app/views/admin/users/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= t(:user_info)%></div>
  <div class="panel-body">
    <p><%= t(:name )%>: <%= @user.name %></p>
	<p><%= t(:u_type )%>: <%= @user.u_type %></p>
	<p><%= t(:email) %>: <%= @user.email %></p>
  </div>

  <!-- Table -->
	<% if @user.is_student? %>
		<%= render :partial => "grades_users" %>
	<% end %>
	<% if @user.is_teacher? %>
		<%= render :partial => "grades" %>
	<% end %>
</div>